name: Synchronize Forks

on:
  push:
    branches:
      - main

jobs:
  curl-command:
    runs-on: ubuntu-latest

    steps:
    - name: Synchronize Site A
      run: >
        curl -L
        -X POST
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.GHP_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/repos/hlxsites/multirepo-site-a/merge-upstream
        -d '{"branch":"main"}'
    - name: Synchronize Site B
      run: >
        curl -L
        -X POST
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.GHP_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/repos/hlxsites/multirepo-site-b/merge-upstream
        -d '{"branch":"main"}'